formasSuma(suma).
formasSuma(sumar).
formasSuma(sume).
formasSuma(sumale).
formasSuma(sumele).
formasResta(resta).
formasResta(restar).
formasResta(reste).
formasResta(restale).
formasResta(restele).
formasDivision(division).
formasDivision(dividir).
formasDivision(divide).
formasDivision(dividele).
formasDivision(dividale).
formasMultiplicacion(multiplicacion).
formasMultiplicacion(multiplicar).
formasMultiplicacion(multiplique).
formasMultiplicacion(multipliquele).
formasMultiplicacion(multiplicale).
formasModulo(modulo).
formasPotencia(elevado).
formasPotencia(eleva).
formasPotencia(elevar).
formasPotencia(eleve).
formasPotencia(elevele).
formasPotencia(elevale).
formasPotencia(potencia).
formasPotencia(potenciado).
formasRaiz(raiz).
formasRaizNumero(cuadrada).
formasRaizNumero(cuadrado).
formasLongitud(largo).
formasLongitud(longitud).
formasLongitud(cantidad).
formasLongitud(elementos).
formasLongitud(cuente).
formasLongitud(cuenteme).
formasLongitud(cuentame).
formasConcatenar(concatenar).
formasConcatenar(concatene).
formasConcatenar(concatena).
formasConcatenar(unir).
formasConcatenar(une).
formasConcatenar(uneme).
formasReverso(reves).
formasReverso(reverso).
formasReverso(reversa).
formasReverso(inversa).
formasReverso(inverso).
formasReverso(invertir).
formasReverso(invierte).
formasReverso(invierteme).
formasReverso(inviertame).
formasReverso(invierta).
formasPrimero(primer).
formasPrimero(primero).
formasPrimero(primera).
formasUltimo(ultimo).
formasMaximo(maximo).
formasMaximo(grande).
formasMaximo(alto).
formasMaximo(maxima).
formasMinimo(minimo).
formasMinimo(minima).
formasMinimo(pequeno).
formasMinimo(bajo).
formasIndice(indice).
formasIndice(posicion).
formasExiste(existe).
formasExiste(encuentra).
formasExiste(encuentre).
formasExiste(esta).
formasEliminar(elimine).
formasEliminar(elimina).
formasEliminar(borrar).
formasEliminar(borre).
formasEliminar(quitar).
formasEliminar(quite).

formasCodigo(codifique).
formasCodigo(codigo).
formasCodigo(codificar).
formasCodigo(escriba).
formasCodigo(escribe).
formasCodigo(escribame).
formasCodigo(escribir).
formasCodigo(generar).
formasCodigo(generarme).
formasCodigo(crear).
formasCodigo(programar).
formasCodigo(programame).
formasCodigo(desarrollar).
formasCodigo(desarrollame).
formasCodigo(produzca).
formasCodigo(produzcame).
formasCodigo(componer).
formasCodigo(compongame).
formasCodigo(construir).
formasCodigo(construyeme).
formasCodigo(elaborar).
formasCodigo(elaboreme).
formasCodigo(fabricar).
formasCodigo(fabricame).