verboMaquina(haga).
verboMaquina(hacer).
verboMaquina(haz).
verboMaquina(hazme).
verboMaquina(resuelva).
verboMaquina(resuelveme).
verboMaquina(calcule).
verboMaquina(calculame).
verboMaquina(calculeme).
verboMaquina(compute).
verboMaquina(computame).
verboMaquina(evalua).
verboMaquina(evaluar).
verboMaquina(evaluame).
verboMaquina(operar).
verboMaquina(operame).
verboMaquina(procesa).
verboMaquina(procesame).